# -*- coding: utf-8 -*-
"""ReverseStringFun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1no27IpIsaRFMeeE45yELAXqTnOWmNHNx
"""

def str_func(userInput):
  return userInput[::-1]
  
userInput = str_func(str(input("Please a String to get reverse string:")))

print(userInput)

