# -*- coding: utf-8 -*-
"""sumofnum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VT5U6PHMekJl1lMuJ35d26HFMuioFmdk
"""

def sumFunc(x):
  total= 0
  for i in x:
    total += i
  return total

print(sumFunc((8, 2, 3, 0, 7)))

